[package]
name = "rrprof"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
wgpu = "24.0"
winit = "0.30"
pollster = "0.4"
bytemuck = { version = "1.21", features = ["derive"] }
env_logger = "0.11"
glam = "0.29" # 行列計算用
